name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Welcome to Actions"
      - name: Print GoodBye
        run: |
          pwd
          echo "Done - Bye"
